name = "hcg-inf"
author = "DVMUJIC"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "530cdf622731ab43fa202e634bd2f8ba343ead43bab4336ff01a1953f151df06"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
